Repository edeckers/react-native-blob-courier, pull requests merged in 2021-12, with the labels that each got.

#178 Enable pull_request workflow trigger
  .github/workflows/ci.yml
Labels: enhancement

#181 Improve Android dependency versioning
  .github/workflows/ci-build-and-test.yml
  android/build.gradle
  android/gradle.lockfile
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/java/io/deckers/blob_courier/fetch/ManagedDownloader.kt
  android/src/main/java/io/deckers/blob_courier/fetch/UnmanagedDownloader.kt
  android/src/main/java/io/deckers/blob_courier/upload/BlobUploader.kt
  android/versions.gradle
  example/android/app/build.gradle
  example/android/app/gradle.lockfile
  example/android/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, dependencies

#175 ci: add npm and pod update scripts
  .github/workflows/upgrade-dependencies.yml
  Makefile
  android/build.gradle
  bin/upgrade-dependencies
  bin/upgrades/run-gradle-upgrades
  bin/upgrades/run-npm-upgrades
  bin/upgrades/run-pod-upgrades
  bin/upgrades/test-npm-upgrades-available
  bin/upgrades/test-pod-upgrades-available
  bin/upgrades/upgrade-npm-packages
  bin/upgrades/upgrade-pods
Labels: enhancement

#177 Fix UploaderParameterFactory type mismatch
  README.md
  android/src/main/java/io/deckers/blob_courier/upload/UploaderParameterFactory.kt
Labels: bug, investigate
